apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
  namespace: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasura
    spec:
      containers:
      - image: hasura/graphql-engine:v1.3.2
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://dmngwiwkkgprnv:077ef3f4108e0b59cd8b18d7c424ee6ec5b07f998575d750bde8adcd57d5fcc6@ec2-52-21-0-111.compute-1.amazonaws.com:5432/dagqvaib17tak0
#         - name: HASURA_GRAPHQL_ADMIN_SECRET
#           value: okok
        ## enable the console served by server
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        ## enable debugging mode. It is recommended to disable this in production
        - name: HASURA_GRAPHQL_DEV_MODE
          value: "false"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
